---
title: "draft"
output: html_document
---

```{r}
require(deSolve)

#implementing model equations
basic<- function (t, y, parms) {
  with(as.list(c(parms)),{
    y=pmax(y,0)
    
    # vectors for each population
    V=y[1:(n)]   
    I=y[n+1]
    U=y[n+2]
    
    # make empty vectors of length n for the derivatives
    dV=rep(0,n)
    dI=0 
    dU=0
    
    #setting up for the hill functions 
    beta=rep(0,n)
    d = rep(0,n)
    
    for(i in 1:n){
       beta[i] = c1*i^m/(phi1^m + i^m)
       d[i] = c2*(1-i^m/(phi2^m + i^m))
    }
    
    # calculate the derivatives
    dV[1] =  +p*I[1] - n*alpha*A*V[1] - beta[1]*U*V[1] - d[1]*V[1]
    
    for(i in 2:(n-1)){
      dV[i] = +(n-(i-1))*alpha*A*V[i-1] - (n-i)*alpha*A*V[i] 
              - beta[i]*U[1]*V[i] - d[i]*V[i]
    }
    
    dV[n] = +alpha*A*V[n-1] - beta[n]*U[1]*V[n] - d[n]*V[n]
    
    dI[1]= + U[1]*(sum(beta[1:n]*V[1:n])) - di*I[1]
    dU[1]= - U[1]*(sum(beta[1:n]*V[1:n]))

# output the derivatives
  dy=c(dV,dI, dU)
   return(list(dy))
  })
}
```

```{r}
#using the functions and plotting 
legend.names = c()

for (n in 1:8){
#defining parameters
p = 10
n = n
alpha = 1 # antibody bounding speed  
A = 10 # antibody amount
di = 0.2 # infected cells dying rate

m = 2
c1 = 5*10^(-5)
phi1 = 5
c2 = 5
phi2 = 5


parms = c(p=p, n=n, alpha=alpha, A=A,di=di,
          m=m, c1=c1, phi1=phi1, c2=c2, phi2=phi2)

#time specification 
time <- seq(0, 18, 0.1)

#initial conditions
statenames <-c(paste('V',1:(n), sep=''), 'I','U')
y <- rep(0, n+2)
names(y)<-statenames
y[grep('I',statenames)]<-10
y[grep('U',statenames)]<-10^6
y[grep('V1', statenames)]<-100


#solving the ode 
out <- as.data.frame(ode(y = y, time = time, basic, parms = parms))

legend.names = append(legend.names, paste0('n = ',n))

if (n==1){
  plot(out$I~out$time, col = n, type = "l", ylim = c(0, 10^6),
     ylab = "Population",xlab = "time (days)", main = "diff n from 1 to 8")
}
else{
  lines(out$I~out$time, col = n)
}

legend("topright", legend = legend.names, lty = 1, col = c(1:8))
}
```


basic model (no hill functions, all constant) 

```{r}
#implementing model equations
basic0<- function (t, y, parms) {
  with(as.list(c(parms)),{
    y=pmax(y,0)
    
    # vectors for each population
    V=y[1:(n)]   
    I=y[n+1]
    U=y[n+2]
    
    # make empty vectors of length n for the derivatives
    dV=rep(0,n)
    dI=0 
    dU=0
    
    
    
    # calculate the derivatives
    dV[1] =  +p*I[1] - n*alpha*A*V[1] - beta[1]*U*V[1] - d*V[1]
    
    for(i in 2:(n-1)){
      dV[i] = +n*alpha*A*V[i-1] - n*alpha*A*V[i] 
              - beta*U[1]*V[i] - d*V[i]
    }
    
    dV[n] = +n*alpha*A*V[n-1] - beta*U[1]*V[n] - d*V[n]
    
    dI[1]= + U[1]*(sum(beta*V[1:n])) - di*I[1]
    dU[1]= - U[1]*(sum(beta*V[1:n]))

# output the derivatives
  dy=c(dV,dI, dU)
   return(list(dy))
  })
}
 

#defining parameters
p = 10
n = 5
alpha = 1 # antibody bounding speed  
A = 10 # antibody amount
di = 0.2 # infected cells dying rate
beta = 5*10^(-5)
d = 5


parms = c(p=p, n=n, alpha=alpha, A=A,di=di,
          m=m, c1=c1, phi1=phi1, c2=c2, phi2=phi2, beta=beta, d=d)

#time specification 
time <- seq(0, 18, 0.1)

#initial conditions
statenames <-c(paste('V',1:(n), sep=''), 'I','U')
y <- rep(0, n+2)
names(y)<-statenames
y[grep('I',statenames)]<-10
y[grep('U',statenames)]<-10^6
y[grep('V1', statenames)]<-100


#solving the ode 
out0 <- as.data.frame(ode(y = y, time = time, basic, parms = parms))
out0
```


```{r}
plot(out0$V5~out0$time, col = "blue", type = "l", ylim = c(0, 10^6),
     ylab = "Population",xlab = "time (days)", main = "Basic Stage Model, n=5")
lines(out0$V1~out0$time, col = "red")
lines(out0$V2~out0$time, col = "orange")
lines(out0$V3~out0$time, col = "yellow")
lines(out0$V4~out0$time, col = "green")
legend("topright", legend = c("V1", "V2", "V3", "V4", "V5"),
       col = c("red","orange", "yellow", "green", "blue"),lty = 1, cex = 0.8)
```














